library(readxl)
data1 <- read_excel("F:/澳门大学/1. ChatGPT项目/Analysis-Peng Xue/数据/All journals database_V3.xlsx")
###Table 2 / Descrptive analysis###
library('compareGroups'); library('haven')
data1$Region <- factor(data1$Region, levels = c("Northern America", "Western Europe", "Other regions"))
data1$ClinicalFocus <- factor(data1$ClinicalFocus, levels = c("General", "Speciality"))
data1$Database <- factor(data1$Database, levels = c("Top journals", "Whole journals"))
data1$A_Category <- factor(data1$A_Category, levels = c("0", "1", "2", "3"),labels = c("No policy","External policy","Own policy","Own & External policy"), ordered = T)
data1$R_Category <- factor(data1$R_Category, levels = c("0", "1", "2", "3"),labels = c("No policy","External policy","Own policy","Own & External policy"), ordered = T)
data1$External <- factor(data1$External, levels = c("0", "1"))
data1$IF <- as.numeric(data1$IF)
data1$CiteScore <- as.numeric(data1$CiteScore)
data1$Eigenefactor <- as.numeric(data1$Eigenefactor)
table2 <- descrTable(Database ~ SJR+IF+CiteScore+Eigenefactor+Region+ClinicalFocus+A_Category+R_Category+External, data = data1, simplify=F, method = c(SJR=2, IF =2, CiteScore=2, Eigenefactor=2))
print(table2)

###Table 3###
AuthoruseY <- data1[data1$A_I1 == "Y", ]
AuthoruseY$A_specificity <- as.numeric(AuthoruseY$A_specificity)
AuthoruseY$A_I2 <- factor(AuthoruseY$A_I2, levels = c("0", "1"))
AuthoruseY$A_I3 <- factor(AuthoruseY$A_I3, levels = c("0", "1"))
AuthoruseY$A_I4 <- factor(AuthoruseY$A_I4, levels = c("0", "1"))
AuthoruseY$A_I5 <- factor(AuthoruseY$A_I5, levels = c("0", "1"))
AuthoruseY$A_I6 <- factor(AuthoruseY$A_I6, levels = c("0", "1"))
AuthoruseY$A_I7 <- factor(AuthoruseY$A_I7, levels = c("0", "1"))
AuthoruseY$A_I8 <- factor(AuthoruseY$A_I8, levels = c("0", "1"))
table3a <- descrTable(Database ~ A_I2+A_I3+A_I4+A_I5+A_I6+A_I7+A_I8+A_specificity, data = AuthoruseY, simplify=F)
print(table3a)
RevieweruseY <- data1[data1$R_I1 == "Y", ]
RevieweruseY$R_specificity <- as.numeric(RevieweruseY$R_specificity)
RevieweruseY$R_I2 <- factor(RevieweruseY$R_I2, levels = c("0", "1"))
RevieweruseY$R_I3 <- factor(RevieweruseY$R_I3, levels = c("0", "1"))
table3b <- descrTable(Database ~ R_I2+R_I3+R_specificity, data = RevieweruseY, simplify=F)
print(table3b)
RevieweruseYN <- data1[data1$R_I1 == "Y" | data1$R_I1 =="N",]
table3b1 <- descrTable(Database ~ R_I1, data = RevieweruseYN, simplify=F)
print(table3b1)
External <- data1[data1$External == "1", ]
table3c <- descrTable(Database ~ COPE+ICMJE+WAME, data = External, simplify=F)
print(table3c)

###Table 4 / Ordinal logistic regression###
Topjournals <- data1[data1$Database == "Top journals", ]
Wholejournals <- data1[data1$Database == "Whole journals", ]
library(nnet);library(car)
fit_Top_A_1 <- multinom(A_Category ~ SJR, data = Topjournals)
cof_Top_A_1<- broom::tidy(fit_Top_A_1)
confint(fit_Top_A_1)
fit_Top_A_2 <- multinom(A_Category ~ Region, data = Topjournals)
cof_Top_A_2<- broom::tidy(fit_Top_A_2)
confint(fit_Top_A_2)
fit_Top_A_3 <- multinom(A_Category ~ ClinicalFocus, data = Topjournals)
cof_Top_A_3<- broom::tidy(fit_Top_A_3)
confint(fit_Top_A_3)
CofTopA <- rbind(cof_Top_A_1,cof_Top_A_2,cof_Top_A_3)

fit_Top_A_4 <- multinom(A_Category ~ IF, data = Topjournals)
cof_Top_A_4<- broom::tidy(fit_Top_A_4)
confint(fit_Top_A_4)
fit_Top_A_5 <- multinom(A_Category ~ CiteScore, data = Topjournals)
cof_Top_A_5<- broom::tidy(fit_Top_A_5)
confint(fit_Top_A_5)
fit_Top_A_6 <- multinom(A_Category ~ Eigenefactor, data = Topjournals)
cof_Top_A_6<- broom::tidy(fit_Top_A_6)
confint(fit_Top_A_6)
CofTopA2 <- rbind(cof_Top_A_4,cof_Top_A_5,cof_Top_A_6)
write.csv(CofTopA2, "CofTopA2.csv")

fit_Top_R_1 <- multinom(R_Category ~ SJR, data = Topjournals)
cof_Top_R_1<- broom::tidy(fit_Top_R_1)
confint(fit_Top_R_1)
fit_Top_R_2 <- multinom(R_Category ~ Region, data = Topjournals)
cof_Top_R_2<- broom::tidy(fit_Top_R_2)
confint(fit_Top_R_2)
fit_Top_R_3 <- multinom(R_Category ~ ClinicalFocus, data = Topjournals)
cof_Top_R_3<- broom::tidy(fit_Top_R_3)
confint(fit_Top_R_3)
CofTopR <- rbind(cof_Top_R_1,cof_Top_R_2,cof_Top_R_3)
fit_Top_R_4 <- multinom(R_Category ~ IF, data = Topjournals)
cof_Top_R_4<- broom::tidy(fit_Top_R_4)
confint(fit_Top_R_4)
fit_Top_R_5 <- multinom(R_Category ~ CiteScore, data = Topjournals)
cof_Top_R_5<- broom::tidy(fit_Top_R_5)
confint(fit_Top_R_5)
fit_Top_R_6 <- multinom(R_Category ~ Eigenefactor, data = Topjournals)
cof_Top_R_6<- broom::tidy(fit_Top_R_6)
confint(fit_Top_R_6)
CofTopR2 <- rbind(cof_Top_R_4,cof_Top_R_5,cof_Top_R_6)
write.csv(CofTopR2, "CofTopR2.csv")


fit_Whole_A_1 <- multinom(A_Category ~ SJR, data = Wholejournals)
cof_Whole_A_1<- broom::tidy(fit_Whole_A_1)
confint(fit_Whole_A_1)
fit_Whole_A_2 <- multinom(A_Category ~ Region, data = Wholejournals)
cof_Whole_A_2<- broom::tidy(fit_Whole_A_2)
confint(fit_Whole_A_2)
fit_Whole_A_3 <- multinom(A_Category ~ ClinicalFocus, data = Wholejournals)
cof_Whole_A_3<- broom::tidy(fit_Whole_A_3)
confint(fit_Whole_A_3)
CofWholeA <- rbind(cof_Whole_A_1,cof_Whole_A_2,cof_Whole_A_3)
fit_Whole_A_4 <- multinom(A_Category ~ IF, data = Wholejournals)
cof_Whole_A_4<- broom::tidy(fit_Whole_A_4)
confint(fit_Whole_A_4)
fit_Whole_A_5 <- multinom(A_Category ~ Eigenefactor, data = Wholejournals)
cof_Whole_A_5<- broom::tidy(fit_Whole_A_5)
confint(fit_Whole_A_5)
fit_Whole_A_6 <- multinom(A_Category ~ CiteScore, data = Wholejournals)
cof_Whole_A_6<- broom::tidy(fit_Whole_A_6)
confint(fit_Whole_A_6)
CofWholeA2 <- rbind(cof_Whole_A_4,cof_Whole_A_5,cof_Whole_A_6)
write.csv(CofWholeA2, "CofWholeA2.csv")

fit_Whole_R_1 <- multinom(R_Category ~ SJR, data = Wholejournals)
cof_Whole_R_1<- broom::tidy(fit_Whole_R_1)
confint(fit_Whole_R_1)
fit_Whole_R_2 <- multinom(R_Category ~ Region, data = Wholejournals)
cof_Whole_R_2<- broom::tidy(fit_Whole_R_2)
confint(fit_Whole_R_2)
fit_Whole_R_3 <- multinom(R_Category ~ ClinicalFocus, data = Wholejournals)
cof_Whole_R_3<- broom::tidy(fit_Whole_R_3)
confint(fit_Whole_R_3)
CofWholeR <- rbind(cof_Whole_R_1,cof_Whole_R_2,cof_Whole_R_3)
fit_Whole_R_4 <- multinom(R_Category ~ IF, data = Wholejournals)
cof_Whole_R_4<- broom::tidy(fit_Whole_R_4)
confint(fit_Whole_R_4)
fit_Whole_R_5 <- multinom(R_Category ~ Eigenefactor, data = Wholejournals)
cof_Whole_R_5<- broom::tidy(fit_Whole_R_5)
confint(fit_Whole_R_5)
fit_Whole_R_6 <- multinom(R_Category ~ CiteScore, data = Wholejournals)
cof_Whole_R_6<- broom::tidy(fit_Whole_R_6)
confint(fit_Whole_R_6)
CofWholeR2 <- rbind(cof_Whole_R_4,cof_Whole_R_5,cof_Whole_R_6)
write.csv(CofWholeR2, "CofWholeR2.csv")

###Supp Table 4/Liner regression###
TopAuthoruseY <- Topjournals[Topjournals$A_I1 == "Y", ]
TopRevieweruseY <- Topjournals[Topjournals$R_I1 == "Y", ]
TopAuthorSpecificity_fit1 <- lm(A_specificity ~ SJR, data = TopAuthoruseY)
summary(TopAuthorSpecificity_fit1)
(ci <- confint(TopAuthorSpecificity_fit1))
TopAuthorSpecificity_fit2 <- lm(A_specificity ~ Region, data = TopAuthoruseY)
summary(TopAuthorSpecificity_fit2)
(ci <- confint(TopAuthorSpecificity_fit2))
TopAuthorSpecificity_fit3 <- lm(A_specificity ~ ClinicalFocus, data = TopAuthoruseY)
summary(TopAuthorSpecificity_fit3)
(ci <- confint(TopAuthorSpecificity_fit3))
TopAuthorSpecificity_fit4 <- lm(A_specificity ~ IF, data = TopAuthoruseY)
summary(TopAuthorSpecificity_fit4)
(ci <- confint(TopAuthorSpecificity_fit4))
TopAuthorSpecificity_fit5 <- lm(A_specificity ~ Eigenefactor, data = TopAuthoruseY)
summary(TopAuthorSpecificity_fit5)
(ci <- confint(TopAuthorSpecificity_fit5))
TopAuthorSpecificity_fit6 <- lm(A_specificity ~ CiteScore, data = TopAuthoruseY)
summary(TopAuthorSpecificity_fit6)
(ci <- confint(TopAuthorSpecificity_fit6))

TopReviewerSpecificity_fit1 <- lm(R_specificity ~ SJR, data = TopRevieweruseY)
summary(TopReviewerSpecificity_fit1)
(ci <- confint(TopReviewerSpecificity_fit1))
TopReviewerSpecificity_fit2 <- lm(R_specificity ~ Region, data = TopRevieweruseY)
summary(TopReviewerSpecificity_fit2)
(ci <- confint(TopReviewerSpecificity_fit2))
TopReviewerSpecificity_fit3 <- lm(R_specificity ~ ClinicalFocus, data = TopRevieweruseY)
summary(TopReviewerSpecificity_fit3)
(ci <- confint(TopReviewerSpecificity_fit3))
TopReviewerSpecificity_fit4 <- lm(R_specificity ~ IF, data = TopRevieweruseY)
summary(TopReviewerSpecificity_fit4)
(ci <- confint(TopReviewerSpecificity_fit4))
TopReviewerSpecificity_fit5 <- lm(R_specificity ~ Eigenefactor, data = TopRevieweruseY)
summary(TopReviewerSpecificity_fit5)
(ci <- confint(TopReviewerSpecificity_fit5))
TopReviewerSpecificity_fit6 <- lm(R_specificity ~ CiteScore, data = TopRevieweruseY)
summary(TopReviewerSpecificity_fit6)
(ci <- confint(TopReviewerSpecificity_fit6))

WholeAuthoruseY <- Wholejournals[Wholejournals$A_I1 == "Y", ]
WholeRevieweruseY <- Wholejournals[Wholejournals$R_I1 == "Y", ]
WholeAuthorSpecificity_fit1 <- lm(A_specificity ~ SJR, data = WholeAuthoruseY)
summary(WholeAuthorSpecificity_fit1)
(ci <- confint(WholeAuthorSpecificity_fit1))
WholeAuthorSpecificity_fit2 <- lm(A_specificity ~ Region, data = WholeAuthoruseY)
summary(WholeAuthorSpecificity_fit2)
(ci <- confint(WholeAuthorSpecificity_fit2))
WholeAuthorSpecificity_fit3 <- lm(A_specificity ~ ClinicalFocus, data = WholeAuthoruseY)
summary(WholeAuthorSpecificity_fit3)
(ci <- confint(WholeAuthorSpecificity_fit3))
WholeAuthorSpecificity_fit4 <- lm(A_specificity ~ IF, data = WholeAuthoruseY)
summary(WholeAuthorSpecificity_fit4)
(ci <- confint(WholeAuthorSpecificity_fit4))
WholeAuthorSpecificity_fit5 <- lm(A_specificity ~ Eigenefactor, data = WholeAuthoruseY)
summary(WholeAuthorSpecificity_fit5)
(ci <- confint(WholeAuthorSpecificity_fit5))
WholeAuthorSpecificity_fit6 <- lm(A_specificity ~ CiteScore, data = WholeAuthoruseY)
summary(WholeAuthorSpecificity_fit6)
(ci <- confint(WholeAuthorSpecificity_fit6))

WholeReviewerSpecificity_fit1 <- lm(R_specificity ~ SJR, data = WholeRevieweruseY)
summary(WholeReviewerSpecificity_fit1)
(ci <- confint(WholeReviewerSpecificity_fit1))
WholeReviewerSpecificity_fit2 <- lm(R_specificity ~ Region, data = WholeRevieweruseY)
summary(WholeReviewerSpecificity_fit2)
(ci <- confint(WholeReviewerSpecificity_fit2))
WholeReviewerSpecificity_fit3 <- lm(R_specificity ~ ClinicalFocus, data = WholeRevieweruseY)
summary(WholeReviewerSpecificity_fit3)
(ci <- confint(WholeReviewerSpecificity_fit3))
WholeReviewerSpecificity_fit4 <- lm(R_specificity ~ IF, data = WholeRevieweruseY)
summary(WholeReviewerSpecificity_fit4)
(ci <- confint(WholeReviewerSpecificity_fit4))
WholeReviewerSpecificity_fit5 <- lm(R_specificity ~ Eigenefactor, data = WholeRevieweruseY)
summary(WholeReviewerSpecificity_fit5)
(ci <- confint(WholeReviewerSpecificity_fit5))
WholeReviewerSpecificity_fit6 <- lm(R_specificity ~ CiteScore, data = WholeRevieweruseY)
summary(WholeReviewerSpecificity_fit6)
(ci <- confint(WholeReviewerSpecificity_fit6))

